version: "3.3"
services:
  app1:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      ZOO_MY_ID: 1
  app2:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      ZOO_MY_ID: 2
  app3:
    build:
      context: ./server
    ports:
      - "5002:5000"
    environment:
      ZOO_MY_ID: 3
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181